### ISSUE TITLE
Ukuran asset tidak sesuai

### ISSUE THREAD

**Issue by liondy** [liondy/BebrasApp#3]
Beberapa asset memiliki ukuran yang tidak sesuai diantaranya
1. karakter bebras tiap orang awalnya kan tanpa kacamata, jadi butuh bebras yang tanpa kacamata
2. beberapa image memiliki lebar ke kiri agak banyak sehingga pada penempatan di HP, gambar tidak di berada di tengah.

Deadline: Minggu, 23 Februari 2020

**Comment by laraimut** [comment]
Button ditengah dan Bebras tanpa aksesoris sudah di selesaikan ya

**Comment by liondy** [comment]
Gw udah coba dan bisa. Nunggu acceptance test dari ko kris sebelum nge close issue ini

**Comment by liondy** [comment]
ini yang di deskripsi uda bener semua ya. gw close aja issue nya
