### ISSUE TITLE
Penyetujuan Database

### ISSUE THREAD

**Issue by liondy** [liondy/BebrasApp#5]
Sampai saat ini, masih belum diketahui apakah dapat menggunakan database. Setelah kemarin mencoba SQLite yang tidak tahu cara pakainya serta package yang tidak update sejak 6 bulan yang lalu, maka agak sangat sulit untuk mengimplementasikannya. Kemarin sempat ngobrol juga dengan Cahyadi bahwa bisa pakai `firebase`, mungkin bisa dilihat2 terlebih dahulu kira2 seperti apa dan apakah sulit untuk diimplementasikan

**Comment by cristine27** [comment]
- sudah ada update ngikutin react native vers 6
- mendukung offline 
- data di simpan dalam JSON
(bakal nyoba pake dull untuk mastiin bisa atau engga)

**Comment by liondy** [comment]
baik silahkan dicoba

**Comment by liondy** [comment]
jadinya tidak pakai database ya..
