### ISSUE TITLE
Penampilan soal

### ISSUE THREAD

**Issue by liondy** [liondy/BebrasApp#8]
Setelah didiskusikan, akhirnya penampilan soal memakai folder.
Jadi di dalam folder asset ada folder soal yang isinya:

- Tahun
- Nomor Soal

Di dalam nomor soal, ada 5 komponen yaitu:
- Deskripsi
- Tantangan
- Pilihan
- Jawaban
- Penjelasan

Semuanya sudah dalam komponen React sehingga hanya perlu di render

**Comment by cristine27** [comment]
siap

**Comment by liondy** [comment]
Ini seharusnya udah ya, cuma memang kita belum ngelengkapin soalnya aja..ntar lah
